# HTTP → redirect to HTTPS
server {
    listen 80;
    server_name ec2-3-110-162-86.ap-south-1.compute.amazonaws.com;

    return 301 https://$host$request_uri;
}

# HTTPS server
server {
    listen 443 ssl;
    server_name 3.110.162.86.nip.io;

    ssl_certificate /etc/letsencrypt/live/3.110.162.86.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/3.110.162.86.nip.io/privkey.pem;

    location / {
        proxy_pass http://app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}